### ISSUE TITLE
Detecting canonical updates

### ISSUE THREAD

**Issue by FischC** [uniqush/uniqush-push#113]
Hi!

Parsing the push response for uniqush-push versions < 2.x I could detect GCM Canonical IDs (https://developers.google.com/cloud-messaging/registration#keeping-the-registration-state-in-sync) and remove the old registrations within my own implementation.
As now in case of "push.DeliveryPointUpdate" only ode "UNIQUSH_SUCCESS" is received there is no longer the possibility to detect this scenario, right?.
Is it possible to introduce a new additional result code, add a new property to ApiResponseDetails and/or add a error message?

Thanks & kind regards
// Clemens

**Comment by mishan** [comment]
@FischC It's definitely reasonable to do. Can you help me understand your use case a bit more, like how you have it set up? Are you keeping track of things in another database for other purposes? If we can understand others' use cases better, we can better enhance the APIs to meet more of these use cases.

**Comment by FischC** [comment]
Dear mishan!

Thanks for your reply. Your assumption (https://github.com/uniqush/uniqush-push/issues/114) is correct, I'm using a custom CRM light system in combination with uniqush push: APP <-> CRM API <-> CRM light system <-> Messaging module <-> uniqush-push!

And the use-case is that I need to flag the contact in case the e.g. App is e.g. no longer installed (dropped in uniqush-push terms), etc.! Thus I trigger some callback URL within the messaging module  to notify the CRM light system in case of UNIQUSH_REMOVE_INVALID_REG,UNIQUSH_UPDATE_UNSUBSCRIBE and errors UNIQUSH_ERROR_NO_DEVICE, UNIQUSH_ERROR_NO_DELIVERY_POINT and UNIQUSH_ERROR_BAD_DELIVERY_POINT. This is working as a charm and maybe my issue could help others to interpret the push responses ... :-)

Unfortunalty some versions of our App still produce canonical IDs (via our CRM API) and in case a canonical ID update in uiqush-push < 2.x occurred, the messaging module informed the CRM system, which then starts some recovery procedures in order to detect duplicated contacts and to resolve this duplicates.
Eventually a new status UNIQUSH_SUCCESS_UPDATED could be introduced indicating that the push was successful and uniqush-push updated the delivery point?

Thanks & kind regards
// Clemens

**Comment by FischC** [comment]
Hi all!

push#113 solved this issue for me ;-)

Thanks
// Clemens
