### ISSUE TITLE
Error: package code.google.com/p/goconf/conf: unable to detect version control system for code.google.com/ path

### ISSUE THREAD

**Issue by FischC** [uniqush/uniqush-push#115]
Hi!

I'm trying to contribute to uniqush regarding issue #113, but as I'm brand new to go and the go build process, I'm currently totally stuck with error "package code.google.com/p/goconf/conf: unable to detect version control system for code.google.com/ path"!

It doesn't make a difference if I call:
go get github.com/uniqush/uniqush-push
or
run ./build-uniqush-push.sh (from my git clone in "uniqush-push/build")

I've search the code and go folders up and down but couldn't find any reference to "code.google.com/p/goconf". Maybe it's just a stupid mistake of me but please advice - Thanks!

Cheers
// Clemens

go version: go version go1.6.2 darwin/amd64
uname -a: Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

**Comment by TysonAndre** [comment]
https://www.socketloop.com/tutorials/golang-all-update-packages-with-go-get-command

Try go get -u all
Or just go get -u github.com/uniqush/uniqush-push
(And everything else from uniqush and monnand)

**Comment by FischC** [comment]
Hi!

Thanks for you hint's. Following your link and digging further I found out that somehow I was on branch "go1" (as go get uses git in the background) :-(
So after "get -u github.com/uniqush/uniqush-push" changed into uniqush-push directory, ran command "git checkout master" and now uniqush push build fine.

Cheers
// Clemens
