### ISSUE TITLE
Migration problem with version 2.x

### ISSUE THREAD

**Issue by Uscher1** [uniqush/uniqush-push#118]
Thank you for maintaining uniqush! 

The full APNS payload is important to me, so I upgraded uniqush from version 1.5.2 to 2.1.0. And I also did the migration command URL: /rebuildserviceset.

For APNS it worked fine, but GCM pushes were not delivered anymore. The log is:
`[Push][Info] 2016/05/03 15:51:44 RequestId=5728acf0-HsY2tFkTaKrdpKovS92c1Q== From=127.0.0.1:45544 Service=ajoy NrSubscribers=1 Subscribers="[myAndroidNumber]"
[Push][Error] 2016/05/03 15:51:44 RequestID=5728acf0-HsY2tFkTaKrdpKovS92c1Q== Service=ajoy Subscriber= PushServiceProvider=gcm:myPspNumber DeliveryPoint=Unknown Failed: BadPushServiceProvider gcm:myPSPNumber
`

Then I checked the psps and I saw only the APNS entry. 
`{"services":{"aJoy":[{"addr":"gateway.push.apple.com:2195","cert":"/mylocalserverpath/myCert.pem","key":"/mylocalserverpath/myKey.pem","service":"aJoy"},{"addr":"gateway.push.apple.com:2195","cert":"/etc/uniqush/sandbox/myCert.pem","key":"/etc/uniqush/sandbox/myKey.pem","service":"aJoy"}],"ajoy":[{"addr":"gateway.push.apple.com:2195","cert":"/etc/uniqush/production/myCert.pem","key":"/etc/uniqush/production/myKey.pem","service":"ajoy"},{"apikey":"myAPIKey","projectid":"myProjectID","service":"ajoy"},{"addr":"gateway.sandbox.push.apple.com:2195","cert":"/etc/uniqush/sandbox/myCert.pem","key":"/etc/uniqush/sandbox/myKey.pem","service":"ajoy"}]},"code":"UNIQUSH_SUCCESS"}
`

I tried to add the GCM psp again.
`curl http://localhost:9898/addpsp -d service=ajoy -d pushservicetype=gcm -d projectid=myProjectID -d apikey=myAPIKey
{"type":"AddPushServiceProvider","date":1462296389,"status":0,"details":{"service":"ajoy","from":"127.0.0.1:48268","pushServiceProvider":"gcm:pushServiceProviderNumber","code":"UNIQUSH_SUCCESS"}}`
But when I checked the psps again, the GCM entry was still missing and GCM push still did not work.

The migration did also fail with version 2.0.0. Finally I reverted uniqush back to version 1.5.2 and it worked again.

**Comment by mishan** [comment]
@Uscher1 Have you tried sending a push? It looks like the GCM PSP is there from your output:

`{"apikey":"myAPIKey","projectid":"myProjectID","service":"ajoy"},`

@TysonAndre thoughts?

**Comment by Uscher1** [comment]
Yes, when I tried so send a push I get the the error I listed in the first log block above
`[Error] 2016/05/03 15:51:44 RequestID=5728acf0-HsY2tFkTaKrdpKovS92c1Q== Service=ajoy Subscriber= PushServiceProvider=gcm:myPspNumber DeliveryPoint=Unknown Failed: BadPushServiceProvider gcm:myPSPNumber`
which shows a missing subsciber, a missing delivery point and an error BadPushServiceProvider.

And yes, I overlooked the short GCM part of the PSP output in the middle. So this seems to be OK.

**Comment by mishan** [comment]
@Uscher1 Can you dig into your Redis DB a bit to clear some things up?

You can run the following with `redis-cli`

`SMEMBERS services{0]`
`KEYS push.service.provider:*` (provided you're OK with running KEYS on your Redis server -- it's an expensive operation but if it's not under much load it should be OK to run it. I usually only do this on dev / stage environments.)

**Comment by Uscher1** [comment]
This is the result (DB used with Uniquish 1.5.2)
`redis 127.0.0.1:6379> SMEMBERS services{0]`
`(empty list or set)`
`redis 127.0.0.1:6379> KEYS push.service.provider:*`
`1) "push.service.provider:apns:0c3ba530e7b0a4b6848b411fc115415ab8821aec"`
`2) "push.service.provider:gcm:6ce5b2f53df06067b4744d81efbdd31efbe7c5ea"`
`3) "push.service.provider:apns:0ae509486cdf208188aafa633d5a6660ad5d4db8"`
`4) "push.service.provider:apns:980b5e38a4d563d98d9a543ac0b0d191db9b5991"`
`5) "push.service.provider:apns:85532e46d56583e1d66a0c07be4eb27a4d325ef7"`

**Comment by mishan** [comment]
Can you run `GET` on each of those `push.service.provider:...` keys? Or if it's just the GCM one giving trouble, you should just be able to run `GET` on that one to get all the details about it. You'll probably want to obfuscate some of the details as you have been before posting that output in this issue :)

Sorry, I also typo'd the `SMEMBERS` command -- it should be `SMEMBERS services{0}`. 1.5.x doesn't have this set, but if you ran the migrate command (rebuildserviceset) earlier it should have created it. Can you run that just to verify?

Sorry that the 2.x upgrade hasn't been smooth for you -- we'll work on fixing this asap. Having this information from your Redis DB should aid resolution.

Thanks!

**Comment by TysonAndre** [comment]
First: Uniqush is case sensitive. You seem to have two services, one named `ajoy`, another named `aJoy`?


> Then I checked the psps and I saw only the APNS entry. 
> `"ajoy": [..., {"apikey":"myAPIKey","projectid":"myProjectID","service":"ajoy"},...]`

The JSON entry with keys "apikey", "projectid", and "service" is a GCM entry. 
The other entries with keys "addr","cert", and "key" are APNS entries.

Side note: one of the APNS entries seems like it should be added with sandbox flag (Server should be gateway.sandbox.push.apple.com). Also, I'd recommend using a different service name for sandbox pushes (uniqush will attempt to send to both production APNS and the sandbox APNS, which will cause the other APNS connection to close).


```
{"addr":"gateway.push.apple.com:2195","cert":"/etc/uniqush/sandbox/myCert.pem","key":"/etc/uniqush/sandbox/myKey.pem","service":"aJoy"}
```

**Comment by TysonAndre** [comment]
What was the curl command you used to send pushes? Was it a wildcard or individual push?

Also, the /rebuildserviceset api wouldn't matter. It was added only to make querying all subscribers possible without needing to provide a comma separated list of service names.

Also, what is the output of 

`curl http://127.0.0.1:9898/subscriptions -d services=ajoy,aJoy -d subscriber=uniqush.client` (With the same subscriber param as you used for pushes.

**Comment by TysonAndre** [comment]
@Uscher1 I suspect this might be related to GCM code and/or the golang libraries used to build the newest release.



http://stackoverflow.com/questions/12619759/google-gcm-server-returns-unauthorized-error-401 suggests this problem may occur when the server uses IPV6, or if the server ip hasn't been whitelisted. 
It might have something to do with our releases using a newer version of the golang library. 

What does https://code.google.com/apis/console/#project:[YOUR PROJECT NUMBER]:access say about whitelisted IP addresses?

```go
	case 401:
		err := push.NewBadPushServiceProvider(psp)
		res := new(push.PushResult)
		res.Provider = psp
		res.Content = notif
		res.Err = err
		resQueue <- res
		return
```


/rebuildserviceset is very likely unrelated, but can you fetch the list of subscribers when leaving out `services=`? `curl http://127.0.0.1:9898/subscriptions -d subscriber=uniqush.client` (With the same subscriber param as you used for pushes)

**Comment by Uscher1** [comment]
Thank you for your investigations!
I checked your proposals and finally managed it to get it work again for GCM by adding also the **IPV6 server address to the GCM server IP whitelist**. So it seems that uniqush from version 2 on accesses the GCM server using IPV6.
And by the way I also did the cleanup of obsolete PSP entries.
Now I am a happy user of the latest Uniqush again. :)
