### ISSUE TITLE
Cannot send any push notification

### ISSUE THREAD

**Issue by aliasbody** [uniqush/uniqush-push#119]
Hello Everyone,

So I followed the installation tutorial and everything.
I've installed redis from the Debian 8 repositories (Version Redis 2.8.17 (00000000/0) 64 bit)
Then I've installed the latest binary from uniqush (uniqush-push 2.1.0)
Started the server (service redis-server start)
And finaly started the uniqush-push file.

When everyone was OK I launched some CURL tests to see the result.
```
root@libredev:~# curl http://127.0.0.1:9898/version
uniqush-push 2.1.0
```

And then I started to follow the tutorial in order to enable iOS Push Notifications:
`curl http://127.0.0.1:9898/addpsp -d service=myproject -d pushservicetype=apns -d cert=/root/apns-dev-cert.pem -d key=/root/apns-dev-key-noenc.pem`

Then I created a subscriber with my Device Token
`curl http://127.0.0.1:9898/subscribe -d service=myproject -d subscriber=uniqush.client -d pushservicetype=apns -d devtoken=14bfd129895f22288d8a9bfc17bcad3160ca6359f51fe4a2fc6bc012dfb1e6ae`

Then I tried to push something to my iOS device (with the application closed of course)
`curl http://127.0.0.1:9898/push -d service=myproject -d subscriber=uniqush.client -d msg="Hello World"`

But nothing happened. I've tried everything but nothing works.

This is what I've done to create the Development Certificate: 
https://blog.serverdensity.com/how-to-renew-your-apple-push-notification-push-ssl-certificate/

I've even tried, on the addpsp fonction, to select the "final cert.pem" (the one with the private key already in it), but nothing works.

After that I've installed Pusher() and I've tested it in a sandbox with the same key and the push notification was received on the iOS. 

So where could the problem come from?

**Comment by liyp** [comment]
hi @aliasbody ,

It seemed that you missed a parameter `-d sandbox=true` when adding Push Service Provider with the development certificate.

The official [usage document](http://uniqush.org/documentation/usage.html) described as follows.

> sandbox
> Optional. true for sandbox; otherwise for production environment

**Comment by mishan** [comment]
@aliasbody did @liyp 's answer solve your issue? Please close the issue if so.

**Comment by aliasbody** [comment]
Hi @liyp  and @mishan, Sorry for taking so long to answer.
When I tested at that time it didn't solved my problem, neither with sandbox at true or false, either with the production or development certificate. I've solved my issue by developing a PHP module in order to do the work.

Once again thank you for everything.
