### ISSUE TITLE
why uniqush need private key for APNS? 

### ISSUE THREAD

**Issue by parasteh** [uniqush/uniqush-push#120]
I know it is good to post here, please forgive me. 

I have a logical problem, why it is necessary to put private -key for APNS service? is it safe to do that ?

**Comment by mishan** [comment]
How else would it work?

https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

See `Provider-to-APNs Connection Trust`

You should follow best practices as far as key storage. Make sure it is not world-readable for example.
