### ISSUE TITLE
Requests to GCM should implement a timeout

### ISSUE THREAD

**Issue by TysonAndre** [uniqush/uniqush-push#124]
(in https://golang.org/pkg/net/http/#Client allows a Timeout to be specified. 
If no timeout is specified, then there is no timeout, and connections may be left open forever.
TLS dialing seems like it already has default timeouts.

`func (self *gcmPushService) multicast` should be changed

**Comment by gtrevg** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  gtrevg@gmail.com
    Domain plentyproductions.com has exceeded the max emails per hour (202/200 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:34925 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server21.abstractdns.com with esmtps (TLSv1:DHE-RSA-AES256-SHA:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bJ0DA-0008MG-KX
	for github@trevorgattis.com; Fri, 01 Jul 2016 15:18:32 +0000
Date: Thu, 30 Jun 2016 12:10:06 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1467313806;
	bh=6c/zeHz3AtZvkGbH8YSlWkDLG1KsjhhuaiR4IKX4kiI=;
	h=From:Reply-To:To:Cc:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=kDbr3Ov3mEJUdZ9J0o7F8bqTLm58r+HhiISSVDXPUCWHpptbPQZ8MePnsElbNZjFV
	 ASX0h8PK3/4EnBtmCAxq5Ts9QECFf4gbi8k9Au0fcfjeFdhYGpeh3LyAPtitZx+sNr
	 PAhGfNZmxHRfH8Rs4ktoedZqP5UD9pG5jQhn30a8=
