### ISSUE TITLE
Build procedure

### ISSUE THREAD

**Issue by kartlee** [uniqush/uniqush-push#128]
Hi Folks,

I find this project interesting and planned to use in one of my project. I wanted to build myself under darwin and play with it. Can you please point me to the documentation for the build procedure? I tried checking out the code from master and build with the script given in build/build-uniqush-push.sh. This started giving me issues related to 'code.google.com...' and more. Please point me to the recommended instructions to build it.

-Kartlee

**Comment by TysonAndre** [comment]
This took a while to figure out. I think we need to add a "go2" tag to the latest version of uniqush-push, etc. for the dependencies.

By default, it's checking out "go1". I thought it'd be getting the latest version, or latest code marked as a relase.

https://github.com/golang/go/wiki/PackagePublishing

**Comment by TysonAndre** [comment]
See the build script update from https://github.com/uniqush/uniqush-push/pull/129 .

The build script we were using used git clone instead of go get, so this wasn't noticed.

**Comment by kartlee** [comment]
Thanks for fixing it. I am able to build the binary for mac using the checked in script.
