### ISSUE TITLE
is this project still alive ?

### ISSUE THREAD

**Issue by p365labs** [uniqush/uniqush-push#147]
is this project still alive ?

**Comment by mishan** [comment]
It most certainly is -- Tagged, hi5, and WeChill (products of if(we) / The Meet Group) are all using it just to name my own company's products.

**Comment by p365labs** [comment]
Hi @mishan thank you for the answer, I didn't want to be rude. I would just like to know if this project is actively maintained as the last commit is from 31st of October 2016, there are issues opened in September (2016) still unanswered, the same for PRs.
