### ISSUE TITLE
NATS Message BUS

### ISSUE THREAD

**Issue by joeblew99** [uniqush/uniqush-push#159]
Would a NATS message queue using protobufs be accepted as a PR ?

This means you can talk to the Push server usng:
- over protobuf and any transport you want (QUIC, HTTP2, etc)
- over NATS using protobuf

There are many NATS wrappers also like web sockets etc too that can be used.

The reason for this ?
- So that this can be easily integrates into microservices or manual orchestration.
- Uses protobuf so that it can be used from any other language. Not really my goal but useful for others.

At the code level this would involves 2 aspects:
- Providing protobuf API that talks to the PUSH server
 - a Proxy to talk to it
 - a cli to talk to it.

- a Nats service to to pub sub between the PUSH server and nats.

**Comment by TysonAndre** [comment]
It's unlikely to be included

- None of the maintainers use or have used NATS, so it probably will be unmaintained
- this adds maintainance work keeping request/response up to date for additional protocols
