### ISSUE TITLE
GCM Deprecated. Do I need to re-subscribe all my users? 

### ISSUE THREAD

**Issue by zanderisrael** [uniqush/uniqush-push#212]
From what I understand FCM and GCM apis are the same.
Will there be an update to uniqush to route all gcm requests to fcm? sort of an alias...

**Comment by TysonAndre** [comment]
The URL for GCM pushes changed to an equivalent URL endpoint that won't be shut down, as part of the 2.6.0 release.

According to Google, GCM tokens will continue to work indefinitely, but the Android GCM SDK won't support the latest Play store SDKs, so they recommend switching to FCM SDKs. GCM and FCM can't coexist on an app installation.

- I'd suggest creating a new FCM PSP in Uniqush for the same service or a different service

Moving this discussion to https://github.com/uniqush/uniqush-push/issues/210
