### ISSUE TITLE
after enter uniqush-push  not show any result 

### ISSUE THREAD

**Issue by vahidalvandi** [uniqush/uniqush-push#232]
after enter start not show any start message ! 

cent os 6.9

**Comment by TysonAndre** [comment]
I need more details to answer your question

- What uniqush-push version are you using?
- What are the contents of your config file? Your WebFrontend logging config should contain info/standard or debug level logging  (or less) if you want to see those logs.
- What CLI command were you using?
- What was dumped to the log file? Do those logs include the start message
  - If the log file can be created, uniqush will dump all logs to that file, including the log line such as `[WebFrontend][Info] 2018/08/20 09:42:13 [Start] localhost:9898`
- Does the user you're using to run uniqush-push have permission to write to the configured log file?

https://github.com/uniqush/uniqush-push/blob/2.6.1/restapi.go#L566-L569
