### ISSUE TITLE
Delivery Success but not receiving on device.

### ISSUE THREAD

**Issue by Lube** [uniqush/uniqush-push#234]
I subscribe correctly and the message gets delivered correctly in iOS, but not on android.

Any help?

[Push][Info] 2018/08/24 20:58:44 RequestID=5b807184-OMVeEChySKhLWxZZEg1UCA== Service=promogo Subscriber=lube PushServiceProvider=fcm:ee074643b5ae0c11ee93147348a181e40edaec81 DeliveryPoint=fcm:4c7dbcde37312b03c0fad825a2509642e9150cb7 MsgID=fcm:ee074643b5ae0c11ee93147348a181e40edaec81:0:1535144324485530%fd0791fdf9fd7ecd Success!

**Comment by TysonAndre** [comment]
Note that on Android, you have to implement a push notification handler to actually render the push notification. (For historic reasons)

Have you implemented that handler? Is it receiving any events?

Does it work if you invoke the GCM push notification with the regid and the API keys for GCM?

**Comment by Lube** [comment]
If I curl, I receive the notification correctly:

curl -X POST \
> -H "Authorization: key=..." \
> -H "Content-Type: application/json" \
> -d '{ 
> "registration_ids": [ 
>  "eakUnJYJnM0:APA91bG2rSg_kjGqM74drhxgsbcPJIhPDzOqM7-kXcS9UTczd-dzWGr-pIg7hgF_Sw113DVuYOhOPqjH1MUS26NJJQ6oGU3Ig7w8RpFFcBnLXk7-8NZaPulv4gGkNkKJsg0MnsHUhnkw"
> ], 
> "data": { 
> "message": "Manual push notification from Lube"
> },
> "priority": "high"
> }' \
> https://android.googleapis.com/gcm/send

If i use the regid to subscribe to a service and send a notification, I do not receive it, any idea what could be happening, or how to debug, besides the log file?

**Comment by TysonAndre** [comment]
If you have designed the Android app in a way that expects "message", you may wish to use uniqush.payload.gcm/uniqush.payload.fcm. See http://uniqush.org/documentation/usage.html

**Comment by Lube** [comment]
I started reading my adb logcat and that was it, the field needs to be message to work both on android and ios.

**Comment by Lube** [comment]
Should I make a pull request updating that on the docs? Or was it a problem in my end?

**Comment by TysonAndre** [comment]
It's a problem on your end, mostly.

"msg" becomes an APNs push notification "msg" and a GCM push notification's field `"data": {"msg": ...}`. GCM doesn't transform most of the fields.
