### ISSUE TITLE
How to test http2?

### ISSUE THREAD

**Issue by strong84** [uniqush/uniqush-push#246]
I added `bundleid` in addpsp.
and added `uniqush.http=1` when push.

I used following cmd on macOS:
`curl -i --http2 http://127.0.0.1:9898/push -d service=http2service -d subscriber=testsubscriber -d msg="Hello World" -d uniqush.http=1`

but still get `HTTP/1.1 200 OK`

**Comment by TysonAndre** [comment]
The release notes were incorrect. They should say `uniqush.http2=1`.

HTTP2 is for using HTTP2 for communication from uniqush to APNs, not for communication from the API client to uniqush (not supported). The reason to use http2 for communication with APNs is to support new APNs features as well as a larger supported JSON payload size

```
srv/apns/push_service.go
243:    if http2, ok := notif.Data["uniqush.http2"]; ok && http2 == "1" {
```

**Comment by strong84** [comment]
Got it!
Save my day🎉🎉🎉
Thanks a lot!!!
