### ISSUE TITLE
APNS Add psp "addr" setting bug 

### ISSUE THREAD

**Issue by sid-dob** [uniqush/uniqush-push#249]
There is a bug in the code because of which if you set `sandbox=false` it does not set the address as it is supposed to. Below is the link to the line : 

https://github.com/uniqush/uniqush-push/blob/b5ab88a392399d859aff4d18a57689f30df14fa3/srv/apns/push_service.go#L141

I would have fixed and sent a PR, unfortunately I have 0 experience in go.

Thanks

**Comment by sid-dob** [comment]
Is there a release panned for the same ?

**Comment by TysonAndre** [comment]
Once I've verified that everything else in 2.7.0-dev has no issues on production use cases. This should be out by the end of the month.
