### ISSUE TITLE
Windows phone support

### ISSUE THREAD

**Issue by monnand** [uniqush/uniqush-push#4]
We can't miss it, can we?

**Comment by hSATAC** [comment]
:+1:

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by monnand** [comment]
@zachlatta Well. Unfortunately, no. I am currently focusing on the bugs in APNS module. Probably will work on this once I got a Windows Device.

**Comment by TysonAndre** [comment]
Something I saw in the news a while ago: https://www.windowscentral.com/microsoft-turning-push-notifications-windows-phone-75-and-80

> Microsoft says that Windows Phone 8.1 and Windows 10 Mobile users will not be affected by this change, as push notifications for those platforms will remain on for the time being. However, once support comes to an end for those platforms as well, it is likely Microsoft will also turn off push notifications there too.

Closing this: It seems like this platform's notifications might disappear entirely in the future, and there has been no work on this issue for years. Additionally, none of the maintainers own a windows phone (to my knowledge)
