### ISSUE TITLE
apns bulk sent problem

### ISSUE THREAD

**Issue by eminden** [uniqush/uniqush-push#56]
I am getting the following error messages after trying to send ~ 12K messages at once using the -d subscribers=\* switch, at first sight i thought it is getting failed 20 secs after receiving the push request, any suggestions?

[Push][Info] 2014/12/05 17:22:36 RequestId=5481cdbc-lVovkUXZnkdyEESlJtweSw== From=127.0.0.1:57883 Service=ios NrSubscribers=1 Subscribers="[*]"
[Push][Error] 2014/12/05 17:22:56 RequestID=5481cdbc-lVovkUXZnkdyEESlJtweSw== Service=ios Subscriber= PushServiceProvider=apns:50a00baec3fb2191f08de251c42f46c8c1ff3542 DeliveryPoint=Unknown Failed: error on connection with 17.172.233.37:2195: write tcp 17.172.233.37:2195: broken pipe. Will retry within 20s
[Push][Info] 2014/12/05 17:22:56 Connection closed by APNS: EOF
[Push][Info] 2014/12/05 17:22:56 Connection closed by APNS: EOF
[Push][Info] 2014/12/05 17:22:57 Connection closed by APNS: EOF
[Push][Info] 2014/12/05 17:22:57 Connection closed by APNS: EOF
[Push][Error] 2014/12/05 17:22:57 RequestID=5481cdbc-lVovkUXZnkdyEESlJtweSw== Service=ios Subscriber= PushServiceProvider=apns:50a00baec3fb2191f08de251c42f46c8c1ff3542 DeliveryPoint=Unknown Failed: error on connection with 17.172.234.16:2195: use of closed network connection. Will retry within 20s
[Push][Error] 2014/12/05 17:22:57 RequestID=5481cdbc-lVovkUXZnkdyEESlJtweSw== Service=ios Subscriber= PushServiceProvider=apns:50a00baec3fb2191f08de251c42f46c8c1ff3542 DeliveryPoint=Unknown Failed: error on connection with 17.172.232.40:2195: use of closed network connection. Will retry within 20s
[Push][Error] 2014/12/05 17:22:57 RequestID=5481cdbc-lVovkUXZnkdyEESlJtweSw== Service=ios Subscriber= PushServiceProvider=apns:50a00baec3fb2191f08de251c42f46c8c1ff3542 DeliveryPoint=Unknown Failed: error on connection with 17.172.233.39:2195: use of closed network connection. Will retry within 20s

**Comment by eminden** [comment]
@monnand  I see some activity on the project, thats why i am asking is there any development/fix regarding this issue?

**Comment by mishan** [comment]
@eminden My company is working on using uniqush-push -- it works great for GCM but has bugs with APNS. There's also option B of migrating all iOS clients to just use GCM which makes life a bit easier in the long run: https://cloud.google.com/solutions/mobile/ios-push-notifications/

We've submitted some fixes but there's still some stuff with apns.go that has some issues.

**Comment by TysonAndre** [comment]
This is unlikely to be an issue anymore.

In march 2016, we switched the push implementation to APNS to use a worker pool instead of a buggy connection pool. See https://github.com/uniqush/uniqush-push/pull/102

https://github.com/uniqush/uniqush-push/pull/149 will allow sending pushes over the new HTTP2 API, which will eventually make this obselete.

**Comment by TysonAndre** [comment]
Haven't seen any comments about this issue in the new releases, which were changed in march 2016 as described in my previous comment: https://github.com/uniqush/uniqush-push/issues/56#issuecomment-312052614

Also, there's now support in Uniqush for APNS's HTTP2 provider API, which doesn't disconnect you after a single invalid token, unlike the binary provider API. See https://github.com/uniqush/uniqush-push/issues/157
