### ISSUE TITLE
Memory leak in apns.go

### ISSUE THREAD

**Issue by or-else** [uniqush/uniqush-push#59]
please add
```defer close(resChan)```
at line 810 in `resultCollector` at https://github.com/uniqush/uniqush-push/blob/master/srv/apns.go

otherwise the go routine waiting on reading from the `resChan` gets stuck forever. Thanks

**Comment by monnand** [comment]
Thanks for your help! Since you discovered this bug. Do you mind to make this change and send me a pull request? I just want to make sure that you have the credit in the commit history. You may want to mention this issue in your commit log.

**Comment by or-else** [comment]
https://github.com/uniqush/uniqush-push/pull/60

**Comment by monnand** [comment]
Closed by #60
