### ISSUE TITLE
Remove expired registrations on send

### ISSUE THREAD

**Issue by ItsNotYou** [uniqush/uniqush-push#70]
From time to time, we have invalid device registrations, especially if the app was uninstalled. If an app is no longer registered in the target device and a message is pushed to the device, the GCM returns a NotRegistered error message. It would be convenient if the server could remove those outdated registrations from its database.

**Comment by mishan** [comment]
I actually have some code I wrote for this, we ran into a similar issue with InvalidRegistrations that must have come from a botched data migration. I'll put something up soon

**Comment by tonireloaded** [comment]
I am the same issue an another related https://github.com/uniqush/uniqush-push/issues/73

**Comment by mishan** [comment]
@ItsNotYou Are you running the latest uniqush-push? Hopefully as there hasn't been a release in a while. There is a specific handler to the "NotRegistered" GCM error message which creates an unsubscribe update event and drops it from the Redis DB.

It will generate a message in the logs but it is actually getting dropped from the DB.

**Comment by mishan** [comment]
The case I handled (and mean to push upstream) is "InvalidRegistration" when somehow an entirely invalid (as reported back by GCM) device token is used. The current uniqush-push won't drop those but it's an easy fix I will push upstream.

**Comment by mishan** [comment]
I've submitted https://github.com/uniqush/uniqush-push/pull/74

**Comment by ItsNotYou** [comment]
Our version is uniqush-push 1.5.2. Is there a schedule for the next release so we can install, test and give feedback?

**Comment by mishan** [comment]
@ItsNotYou that's the latest, it should already be dropping expired registrations. My patch deals with invalid registrations -- those that were never valid and never will be. In my case, I happened to batch import some bad device tokens.

Can you paste logs?

**Comment by mishan** [comment]
Also good point about new version... There's been some unrelated fixes/improvements introduced since 1.5.2 that would be valuable to release. @monnand what's your opinion? Should we go 1.5.3?

**Comment by TysonAndre** [comment]
1.5.3 was released months ago. Reopen this if there's anything else that still affects the latest release. https://github.com/uniqush/uniqush-push/releases
