### ISSUE TITLE
Broken IOS 8, ISO 9.0.1 push messages 

### ISSUE THREAD

**Issue by securityicon** [uniqush/uniqush-push#72]
Hi,

I have looked at the issues and found the issue #52 closely relate to what I am experiencing now.
https://github.com/uniqush/uniqush-push/issues/52

The issue as far as I can make out is that there is a change since IOS8. In the issue 52 however the push notification was working and once upgraded its broken.

In my scenario however this is not the case. I have a new iPhone6 with IOS 9.0.1
It is not a production app. I am using the sandbox with developer certificates.

I followed the following procedure:

1. I create a new Push service called test 7 with success

Request:
curl http://10.251.20.50:9898/addpsp -d service=test7 -d pushservicetype=apns -d cert=~/development.pem -d key=~/developmentkey.pem -d sandbox=true

Result:
[AddPushServiceProvider][Info] 2015/10/01 14:59:51 From=10.251.20.50:33219 Service=test7 PushServiceProvider=apns:63de0ff92e3ba0c77a8f938f1e95a118a69a5dc1 Success!

2. I register a new subscriber to my test7 service with success
 
Request
curl http://10.251.20.50:9898/subscribe -d service=test7 -d subscriber=subscriber1 -d pushservicetype=apns -d devtoken=4cb6e59ab85869eb067d24158f8fadea31cfc0b5861bb368b2d9c82598e5a4f3

Result:
[Subscribe][Info] 2015/10/01 15:01:01 From=10.251.20.50:33222 Service=test7 Subscriber=subscriber1 PushServiceProvider=apns:63de0ff92e3ba0c77a8f938f1e95a118a69a5dc1 DeliveryPoint=apns:e4e38ba14d1899bd2a61db176b15371b31665278 Success!

3 I submit a test message to the subscriber of the test7 service with some level of success

Request:
curl http://10.251.20.50:9898/push -d service=test7 -d subscriber=subscriber1 -d msg="Hello broken world!"

Result:
[Push][Info] 2015/10/01 15:02:45 RequestId=560d3d05-AeheSSYtqZC5rNy_uCVF2w== From=10.251.20.50:33230 Service=test7 NrSubscribers=1 Subscribers="[subscriber1]"

[Push][Info] 2015/10/01 15:02:46 RequestID=560d3d05-AeheSSYtqZC5rNy_uCVF2w== Service=test7 Subscriber=subscriber1 PushServiceProvider=apns:63de0ff92e3ba0c77a8f938f1e95a118a69a5dc1 DeliveryPoint=apns:e4e38ba14d1899bd2a61db176b15371b31665278 MsgId=apns:apns:63de0ff92e3ba0c77a8f938f1e95a118a69a5dc1-1 Success!

4. In the output above I can see that the APNS service has accepted the request and gave me a valid message ID.

5. After a few milliseconds I presume I get a response from the APNS that there was some error(I am not sure what the detail of these packets are as it is not displayed in the logs)
Uniqush unsubscribes the device based on the error information that it receives.

[Push][Info] 2015/10/01 15:02:46 Service=test7 Subscriber=subscriber1 DeliveryPoint=apns:e4e38ba14d1899bd2a61db176b15371b31665278 Unsubscribe success
[Push][Error] 2015/10/01 15:02:46 Error: <nil>
[Push][Info] 2015/10/01 15:02:46 Connection closed by APNS: EOF

So I have no idea why this is happening or how to fix this? Any ideas welcome.

6. Whenever I try and send to this device again i get an error that the device is not found which makes sense after it has been deregistered.

[Push][Error] 2015/10/01 15:21:22 RequestID=560d4162-9wUQ14toEwtkr4p1hNB64g== Service=test7 Subscriber=subscriber1 Failed: No device

**Comment by jerbob92** [comment]
I also got these errors. I got these errors when I was using the wrong certificates.
APNS responded with message sent, but after a short while it would say "Unsubscribe success" and "APNS: EOF".
You should probably check if sandbox mode is correct and if you are using the correct certificates that belong to the app the user is registering on.

**Comment by mishan** [comment]
What @jerbob92 said -- you need to pass the sandbox params to all those requests.

**Comment by mishan** [comment]
uniqush-push does not store the sandbox flag as part of the Push Service Provider currently, so that does appear to be the problem you are experiencing. Please feel free to re-open this issue if this does not resolve it.

**Comment by jerbob92** [comment]
Is that true? I don't pass the sandbox param on every request and it seems to work fine here.

**Comment by mishan** [comment]
Actually, you're right -- it does store it as part of the volatile data in Redis, my mistake. I would double check the certificate. It seems like an error happens sending the 1st push which then unsubscribes the device from the subscriber. APNS: EOF can be caused by certificate issues.
