### ISSUE TITLE
Different delivery points on Redis DB for the same device

### ISSUE THREAD

**Issue by tonireloaded** [uniqush/uniqush-push#73]
Hi,

I am using uniqush-push on server and app cordova client with phonegap-plugin-push. When app starts, it does a request to GCM (through cordova plugin) and then, other request to uniqush-push server to add a device to subscriber (regID).

If client app is uninstalled / installed, another delivery point is inserted for the same device and I receive duplicate push notifications in my client app.

Thanks.

**Comment by monnand** [comment]
Hi,

sorry for my late reply. This should be a designed feature in GCM/Android system. Each time when you try to get a regID, it will be a unique one. This is different from iOS system. In fact, it is a more secure design considering the scenario where two accounts logged into the same app on the same device. In the case of iOS, these two accounts will share the same device ID and a push notification to any account will be delivered to the device. Then if you remove one account from the device, the device may still receive notifications for the deleted account if the server side is not implemented properly. In fact, IIRIC, it was a real bug of Twitter client on iOS.
