### ISSUE TITLE
"+" sign not showing in IOS notification

### ISSUE THREAD

**Issue by pesseyjulien** [uniqush/uniqush-push#75]
Hi,

Thanks a lot for such a great tool !
I have one small issue using it though, indeed I'm trying to send IOS push notification with the '+' sign in them but it's not working. I have tried other special characters and it seems to be working fine with them.
Any idea why the '+' would not work ?

Thanks in advance for your help,
Julien

**Comment by TysonAndre** [comment]
See http://stackoverflow.com/questions/1005676/urls-and-plus-signs

If you made a request to uniqush URL such as `http://.../push?...&msg=foo+bar`, that's passing the string "foo bar" as the message (Or whatever other field you used a literal `+` in).

Call urlencode on the values of each param before making a request to uniqush. `http://.../push?...&msg=foo%2Bbar` should cause a plus sign to show up in the message.
