### ISSUE TITLE
Look into using go-redis

### ISSUE THREAD

**Issue by mishan** [uniqush/uniqush-push#94]
Right now we're using uniqush's own Redis library, it's worth looking into libraries supported by the community such as go-redis

https://github.com/go-redis/redis

One nice thing about go-redis is we could support talking to a sharded Redis setup directly instead of having to use twemproxy/nutcracker.

**Comment by TysonAndre** [comment]
We switched from monnand's library to redis.v3 already - https://github.com/uniqush/uniqush-push/blob/master/db/pushredisdb.go
