### ISSUE TITLE
Redis connection can get into bad state and not recover

### ISSUE THREAD

**Issue by mishan** [uniqush/uniqush-push#97]
This is something we've observed on production once in a while and @TysonAndre is looking into.

When this happens, the same outgoing port keeps failing, so the connection is never re-established. The only remedy currently is to restart the instance.

**Comment by TysonAndre** [comment]
Solutions: 

1. If a connection has an error, always close it and never return it to the queue https://github.com/monnand/goredis/pull/5
2. https://github.com/uniqush/uniqush-push/issues/94

**Comment by TysonAndre** [comment]
We migrated to redis.v3 , see https://github.com/uniqush/uniqush-push/issues/94
